### ISSUE TITLE
login seems to be broken

### ISSUE THREAD

**Issue by prldm** [bczsalba/asztal-images#1]
![image](https://user-images.githubusercontent.com/52859929/100020047-7511f480-2ddf-11eb-95ff-8db12939e62a.png)

`{"error":"invalid_grant","error_description":"invalid_username_or_password"}`

I'm sure I didn't make a typo, all the credentials are correct, they're working in browser

**Comment by bczsalba** [comment]
That error comes from Kréta themselves, and Asztal doesn't do anything to your credentials so it might be something on their side.

Try removing your storage/usercfg.py file, and signing in again, maybe something went wrong there.

There seem to be some school limitations on Kréta's side, so if the other things don't work out we can look into that!

Thank you for trying Asztal, hopefully you can like actually use it soon :D

**Comment by prldm** [comment]
Ah fk, I opened the issue in a wrong place :|
But nvm, I tried out deleting the config file, didn't help, still gives me the same error.
Another weird thing is when I try to obtain the access/refresh tokens using the curl command from your other kreta project, that gives me the same error
![image](https://user-images.githubusercontent.com/52859929/100022067-d4253880-2de2-11eb-95e7-7c214499a7a2.png)

**Comment by bczsalba** [comment]
Yeah that would've been my next idea too, weird that it doesn't work. 

Unfortunately as far as I'm aware that's the only way to access the data, maybe your school specially blocked something? 

Try the curl command [here](https://github.com/bczsalba/ekreta-docs-v3#getting-list-of-all-kreta-schools), and grep for your school. See the featureToggleList field, maybe something useful is in there.

Also important, does the Kréta app work for you? It should be using about the same system, so that can be telling.

**Comment by prldm** [comment]
Oh god, I'm so stupid. lol
I used the `instituteId` instead of the `instituteCode`, thought it works by the Id
but I still had to change `ekreta.hu` to `e-kreta.hu` in the code, my school is only accessible by this domain.

**Comment by bczsalba** [comment]
Okay, that explains it! :D

Although the domain thing is weird, I thought that domain was only used for the old API.

In the near-ish future I'm planning on releasing the finalized version of Asztal, which will have all kinds of fancy stuff like full custom color profiles, ability to use the interface with any API and stuff like it, I'll try to look into it then.

Thank you!
